Fix build check
Signed-off-by: Max Shaposhnik <mshaposh@redhat.com>

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -68,18 +68,19 @@ jobs:
             git --no-pager diff
             exit 1
           fi
-      - name: Check manifests
-        run: |
-          pip install yq
-          # Note: fmt is necessary after generate since generated sources will
-          #       fail format check by default.
-          make generate fmt manifests
-          if [[ ! -z $(git status -s) ]]
-          then
-            echo "generated sources are not up to date:"
-            git --no-pager diff
-            exit 1
-          fi
+#        Commented out = we doesn't have generated code
+#      - name: Check manifests
+#        run: |
+#          pip install yq
+#          # Note: fmt is necessary after generate since generated sources will
+#          #       fail format check by default.
+#          make generate fmt manifests
+#          if [[ ! -z $(git status -s) ]]
+#          then
+#            echo "generated sources are not up to date:"
+#            git --no-pager diff
+#            exit 1
+#          fi
       - name: Run Go Tests
         run: |
           python -m pip install --upgrade pip yq
